import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home Fresh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGwKCMfcKNe194s09dqCZSpbgYeIj12S78hQ&usqp=CAU" />
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}
